# Generated by Django 4.2 on 2024-12-26 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0002_goods_author_goods_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goods',
            name='like_users',
            field=models.ManyToManyField(related_name='like_goods', to=settings.AUTH_USER_MODEL),
        ),
    ]
